///////////////////////////////////////////////////////////////////////////////
// IOSyncServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_IOSync = 0x3F000000;
#define SRVNAME_IOSYNC "IOSync"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_IOSyncCIOSyncModule = {0x9db963ca,0x876d,0x44a3,{0x83,0x41,0x41,0xd1,0xdb,0xe2,0x89,0xf2}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_IOSyncModuleDefaultAdsPort = 0x00000001;
const PTCID PID_IOSyncModuleCounter = 0x00000003;
const PTCID PID_IOSyncModuleMyContextId = 0x0000000F;
const PTCID PID_IOSyncModuleRTime = 0x00000004;
const PTCID PID_IOSyncModulePostCyclicCaller = 0x00000010;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _IOSyncModuleInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} IOSyncModuleInputs, *PIOSyncModuleInputs;

typedef struct _IOSyncModuleOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} IOSyncModuleOutputs, *PIOSyncModuleOutputs;

#pragma pack(push,1)
typedef struct _IOSyncModuleDebug
{
	SHORT DelayUsec;
	SHORT MaxWaitUsec;
	SHORT NumSyncModule;
	bool SyncFlag0;
	bool SyncFlag1;
	bool SyncFlag2;
} IOSyncModuleDebug, *PIOSyncModuleDebug;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_IOSyncModuleInputs 0
#define ADI_IOSyncModuleOutputs 1
#define ADI_IOSyncModuleDebug 3
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_7EBE6026_0379_47C3_97B9_EC238F447164_INCLUDED_)
#define _TC_IID_7EBE6026_0379_47C3_97B9_EC238F447164_INCLUDED_
TCOM_DECL_INTERFACE("7ebe6026-0379-47c3-97b9-ec238f447164", IIOSyncInterface)
#endif // !defined(_TC_IID_7EBE6026_0379_47C3_97B9_EC238F447164_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
