///////////////////////////////////////////////////////////////////////////////
// IOSyncClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "IOSyncClassFactory.h"
#include "IOSyncServices.h"
#include "IOSyncVersion.h"
#include "IOSyncModule.h"

BEGIN_CLASS_MAP(CIOSyncClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_IOSync, CID_IOSyncCIOSyncModule, SRVNAME_IOSYNC "!CIOSyncModule", CIOSyncModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CIOSyncClassFactory::CIOSyncClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_IOSYNC));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(IOSync));
#endif //defined(TCDBG_UNIT_VERSION)
}

