///////////////////////////////////////////////////////////////////////////////
// PressPositionClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "PressPositionClassFactory.h"
#include "PressPositionServices.h"
#include "PressPositionVersion.h"
#include "PressPosModule.h"

BEGIN_CLASS_MAP(CPressPositionClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_PressPosition, CID_PressPositionCPressPosModule, SRVNAME_PRESSPOSITION "!CPressPosModule", CPressPosModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CPressPositionClassFactory::CPressPositionClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_PRESSPOSITION));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(PressPosition));
#endif //defined(TCDBG_UNIT_VERSION)
}

