///////////////////////////////////////////////////////////////////////////////
// PressPositionServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_PressPosition = 0x3F000000;
#define SRVNAME_PRESSPOSITION "PressPosition"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_PressPositionCPressPosModule = {0x94bc1091,0x676b,0x4998,{0xa5,0xb7,0x96,0x97,0x66,0x54,0xcc,0x00}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_PressPosModuleDefaultAdsPort = 0x00000001;
const PTCID PID_PressPosModuleCounter = 0x00000003;
const PTCID PID_PressPosModuleMyContextId = 0x00000006;
const PTCID PID_PressPosModulePostCyclicCaller = 0x00000004;
const PTCID PID_PressPosModuleIOSyncIntrf1 = 0x00000005;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _PressPosModuleInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} PressPosModuleInputs, *PPressPosModuleInputs;

typedef struct _PressPosModuleOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} PressPosModuleOutputs, *PPressPosModuleOutputs;

#pragma pack(push,1)
typedef struct _PressPosModuleDebug
{
	SHORT ExeTimeUsec;
	ULONG InputReadyTimeoutCount;
	ULONG OutputReadyTimeoutCount;
} PressPosModuleDebug, *PPressPosModuleDebug;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_PressPosModuleInputs 0
#define ADI_PressPosModuleOutputs 1
#define ADI_PressPosModuleDebug 3
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_7EBE6026_0379_47C3_97B9_EC238F447164_INCLUDED_)
#define _TC_IID_7EBE6026_0379_47C3_97B9_EC238F447164_INCLUDED_
TCOM_DECL_INTERFACE("7ebe6026-0379-47c3-97b9-ec238f447164", IIOSyncInterface)
#endif // !defined(_TC_IID_7EBE6026_0379_47C3_97B9_EC238F447164_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
