///////////////////////////////////////////////////////////////////////////////
// RollFeedServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_RollFeed = 0x3F000000;
#define SRVNAME_ROLLFEED "RollFeed"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_RollFeedCRollFeedModule = {0xeef5ccea,0x3262,0x477d,{0xae,0xec,0x6f,0x91,0xa0,0x8b,0xcb,0xed}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_RollFeedModuleDefaultAdsPort = 0x00000001;
const PTCID PID_RollFeedModuleCounter = 0x00000003;
const PTCID PID_RollFeedModuleMyContextId = 0x00000005;
const PTCID PID_RollFeedModulePostCyclicCaller = 0x00000004;
const PTCID PID_RollFeedModuleIOSyncIntrf1 = 0x00000006;
const PTCID PID_RollFeedModuleModPosBitPtr = 0x00000007;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#pragma pack(push,1)
typedef struct _RollFeedModuleInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
	unsigned char TestInputBit0 : 1;
	unsigned char reserved1 : 7;
	ULONG ModPosBitMapped;
	ULONG ModPosBitStart;
	ULONG ModPosBitEnd;
} RollFeedModuleInputs, *PRollFeedModuleInputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _RollFeedModuleOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
	unsigned char TestOutputBit0 : 1;
	unsigned char reserved1 : 7;
} RollFeedModuleOutputs, *PRollFeedModuleOutputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _RollFeedModuleDebug
{
	SHORT ExeTimeUsec;
	ULONG InputReadyTimeoutCount;
	ULONG OutputReadyTimeoutCount;
} RollFeedModuleDebug, *PRollFeedModuleDebug;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_RollFeedModuleInputs 0
#define ADI_RollFeedModuleOutputs 1
#define ADI_RollFeedModuleDebug 3
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_7EBE6026_0379_47C3_97B9_EC238F447164_INCLUDED_)
#define _TC_IID_7EBE6026_0379_47C3_97B9_EC238F447164_INCLUDED_
TCOM_DECL_INTERFACE("7ebe6026-0379-47c3-97b9-ec238f447164", IIOSyncInterface)
#endif // !defined(_TC_IID_7EBE6026_0379_47C3_97B9_EC238F447164_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
