///////////////////////////////////////////////////////////////////////////////
// RollFeedClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RollFeedClassFactory.h"
#include "RollFeedServices.h"
#include "RollFeedVersion.h"
#include "RollFeedModule.h"

BEGIN_CLASS_MAP(CRollFeedClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_RollFeed, CID_RollFeedCRollFeedModule, SRVNAME_ROLLFEED "!CRollFeedModule", CRollFeedModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CRollFeedClassFactory::CRollFeedClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ROLLFEED));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(RollFeed));
#endif //defined(TCDBG_UNIT_VERSION)
}

