///////////////////////////////////////////////////////////////////////////////
// RollFeedInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "RollFeedServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_9C0AF363_67DF_4054_8D25_E35F780F42E3_INCLUDED_)
#define _TC_TYPE_9C0AF363_67DF_4054_8D25_E35F780F42E3_INCLUDED_
struct __declspec(novtable) IIOSyncInterface : public ITcUnknown
{
	virtual bool TCOMAPI GetInputReadyFlag()=0;
	virtual void TCOMAPI SetInputReadyFlag()=0;
	virtual void TCOMAPI ResetInputReadyFlag()=0;
	virtual void TCOMAPI CountInputReadyTimeout()=0;
	virtual bool TCOMAPI GetOutputReadyFlag()=0;
	virtual void TCOMAPI SetOutputReadyFlag()=0;
	virtual void TCOMAPI ResetOutputReadyFlag()=0;
	virtual void TCOMAPI CountOutputReadyTimeout()=0;
};
_TCOM_SMARTPTR_TYPEDEF(IIOSyncInterface, IID_IIOSyncInterface);
#endif // !defined(_TC_TYPE_9C0AF363_67DF_4054_8D25_E35F780F42E3_INCLUDED_)

///</AutoGeneratedContent>
